.travis.yml: add verification of CFLAGS propagation from build log
Fixes #903

Signed-off-by: bkil-syslogng <tamas.nagy@balabit.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,9 +11,22 @@ before_script:
   - ./autogen.sh
   - unset PYTHON_CFLAGS # HACK
   - ./configure CFLAGS=-Werror --with-ivykis=internal --prefix=$HOME/install/syslog-ng --enable-pacct --enable-manpages --with-docbook=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl 
-  - make -j || make V=1 --keep-going # to make error messages more readable on error
+  - . tests/build-log-cflags-propagation.sh;
+    exec_prop_check "make -j V=1";
+    S=$?;
+    if [ "$S" = "42" -o "$S" = "0" ]; then
+      return $S;
+    else
+      make V=1 --keep-going; false;
+    fi # to make error messages more readable on error
 script:
-  - if [ "$CC" = "gcc" ]; then make distcheck V=1; else make func-test V=1; fi
+  - if [ "$CC" = "gcc" ]; then
+      . tests/build-log-cflags-propagation.sh;
+      export CFLAGS="$CFLAGS -Werror";
+      exec_prop_check "make distcheck V=1 --keep-going";
+    else
+      make func-test V=1;
+    fi
 compiler:
   - gcc
   - clang
